spring:
  application:
    name: server

# Default port
server:
  port: 8761

# Eureka Server configuration
eureka:
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 30000
    renewal-percent-threshold: 0.75
    response-cache-update-interval-ms: 60000

  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
